project: 
  type: book
  output-dir: docs
book:
  title: "Dragehode"
  cover-image: Dragehode.png
  page-navigation: true
  chapters: 
    - index.qmd
    - intro.qmd
    - localEst.qmd
    - growthRate.qmd
    - growthRate_meta.qmd
    - codeBook.qmd
    - funksjoner.qmd
    
    
#bibliography: book.bib

format: 
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport