project: 
  type: book
  output-dir: docs
book:
  title: "Dragehode"
  chapters: 
    - index.qmd
    - intro.qmd
    - localEst.qmd
    
    
#bibliography: book.bib

format: 
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport